import os
os.makedirs('docs/mockups', exist_ok=True)
f = open('docs/mockups/login-v4.html', 'w', encoding='utf-8')
f.write('<!DOCTYPE html>\n<html lang="fr">\n<head>\n<meta charset="UTF-8">\n')
f.write('<meta name="viewport" content="width=device-width,initial-scale=1.0">\n')
f.write('<title>TraceO - Connexion</title>\n<style>\n')
f.write(':root{--brand:#0b4a2c;--brand-deep:#083821;--action:#e85d04;--action-hover:#d45303;--bg:#f7f5f2;--bg-elevated:#fff;--text:#1a1a1a;--text-muted:#5c6570;--text-faint:#8b94a0;--border:#e2dcd2;--border-strong:#d0c8bc;--radius:16px;--radius-sm:10px;--font-sans:DM Sans,system-ui,sans-serif;--shadow-sm:0 2px 8px rgba(11,74,44,.06);--shadow-md:0 8px 30px rgba(11,74,44,.10);--shadow-lg:0 20px 60px rgba(11,74,44,.15);--fs-caption:12px;--fs-small:13px;--fs-body:14px;--fs-title:20px;--fs-display:28px}\n')
f.write('*{box-sizing:border-box}html,body{margin:0;padding:0}\n')
f.write('body{font-family:f.write('body{font-family:f.write('body{font-family:f.write('body{font-family:f.write('bigf.write(n')
f.write('.page{display:flex;min-height:10f.write('.page{display:flex;min-height:10f.write('.page{dispntf.write('.page{display:flex;min-height:10f.write('.page{display:flex;min-heigg:3rem;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden}\n')
f.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{contenf.write('.brand::before{co
f.write('.logo .dot{width:12px;height:12px;border-radius:50%;backgrof.write('.logo .dot{width:12px;height:12px;border-radius:50%;backgrof.write('.logo .dot{width:12px;height:12px;border-radius:5rite('.tagline .accent{color:#f59e0b}\n')
f.write('.subtitle{font-size:var(--fs-body);color:rgba(255,255,255,.7);max-width:340px;margin:0}\n')
f.write('.features{margin-top:3rem;display:flex;flex-direction:column;gap:1.25rem}\n')
f.write('.feature{display:flex;gap:14px;align-items:flex-start}\n')
f.write('.feature-icon{width:40px;height:40px;border-radius:10px;background:rgba(255,255,255,.1);display:flex;align-items:center;justify-content:center;font-size:18px;flex-shrink:0}\n')
f.write('.feature-text h4{margin:0 0 2px;font-size:var(--fs-small);font-weight:700}\n')
f.write('.feature-text p{margin:0;font-size:var(--fs-caption);color:rgba(255,255,255,.6)}\n')
f.write('.brand-footer{font-size:var(--fs-caption);color:rgba(255,255,255,.4);position:relative;z-index:1}\n')
f.write('.form-side{width:55%;display:flex;align-items:center;justify-content:center;padding:3rem 2rem}\n')
f.write('.form-card{width:100%;max-width:380px;background:var(--bg-elevated);border-radius:var(--radius);padding:2.5rem;box-shadow:var(--shadow-md)}\n')
f.write('.form-card h2{margif.write('.form-card h2{margif.write('.form-card h2{margif.write('.form-card h2{margif.write('.form-0 0 2rem;color:var(--text-muted);font-size:var(--fs-small)}\n')
f.write('.field{margin-bottom:1.25rem}\n')
f.write('.field label{display:block;font-size:var(--fs-caption);font-weight:600;color:var(--text-muted);margin-bottom:6px;text-transform:uppercase;letter-spacing:.03em}\n')
f.write('.field input{width:100%;padding:12px 14px;border:1.5px solid var(--border);border-radius:var(--radius-sm);font-size:var(--fs-body);font-family:inherit;background:var(--bg);transition:border-color .15s,box-shadow .15s}\n')
f.write('.field input:focus{outline:none;border-color:var(--action);box-shadow:0 0 0 3px rgba(232,93,4,.12)}\n')
f.write('.form-options{display:flex;justify-content:space-between;align-items:center;margin-bottom:1.5rem}\n')
f.write('.checkbox{display:flex;align-items:center;gap:8px;font-size:var(--fs-small);color:var(--text-muted);cursor:pointer}\n')
f.write('.checkbox input{width:16f.write('.checkbox input{width:16f.write('.checkbox input{width:16f.write('.checkbox input{width:16f.write('.checkbox input{width:16f.write('.checkbox input{width:16f.write('.checkbox inputunf.write('.checkbox input{width:16f.write(-flex;align-items:center;justify-content:center;gap:8px;padding:12px 20px;border-radius:var(--radius-sm);font-size:var(--fs-body);font-weight:600;cursor:pointer;border:none;transition:all .15s}\n')
f.write('.btn-primary{width:100%;background:var(--action);color:#fff}\n')
f.write('.btn-primary:hover{background:var(--action-hover)}\n')
f.write('.divider{display:flex;align-items:center;gap:12px;margin:1.5rf.write('.divider{display:flex;align-items:center;gap:12px;margin:1.5rf.write('.divider{display:flex;align-itemnt:"";flex:1;height:1px;background:var(--border)}\n')
f.write('.help-text{text-align:center;font-size:var(--fs-small);color:var(--text-muted);margin:0}\n')
f.write('.help-text a{color:var(--brand);text-decoration:none;font-weight:600}\n')
f.write('@media(max-width:768px){.brand{display:none}.form-side{width:100%}}\n')
f.write('</style>\n</head>\n<body>\n')
f.write('<div class="page">\n')
f.write('  <div class="brand">\n')
f.write('    <div class="brand-inner">\n')
f.write('      <div class="logo"><span class="dot"></span> TraceO&#174;</div>\n')
f.write('      <h1 class="tagline">La tra&#231;abilit&#233; au service de <span class="accent">vos activit&#233;s</span>.</h1>\n')
f.write('      <p class="subtitle">G&#233;rez vos livraisons mat&#233;riaux, suivez chaque livraison en temps r&#233;el et conservez vos preuves.</p>\n')
f.write('      <div class="features">\n')
f.write('        <div class="feature"><div class="feature-icon">&#128205;</div><div class="feature-text"><h4>Suivi temps r&#233;el</h4><p>Chaque livraison tra&#231;e du d&#233;part &#224; la preuve</p></div></div>\n')
f.write('        <div class="feature"><div class="feature-icon">&#128203;</div><div class="feature-text"><h4>Conformit&#233; BC</h4><p>Les produits livr&#233;s restent conformes au bon de commande</p></div></div>\n')
f.write('        <div class="feature"><div class="feature-icon">&#1282f.write('        <div class="fexf.write('        <div class="feat4><p>Photos, certificats et d&#233;clarations du livreur</p></div></div>\n')
f.write('      </div>\n')
f.write('    </div>\n')
f.write('    <p class="brand-footer">&#169; 2026 TraceO. Tous droits r&#233;serv&#233;s.</p>\n')
f.write('  </div>\n')
f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write(33f.write('  <f.write('  <f.write('  </p>\n'f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write('  <f.write(33f.write('  <f.write('  <f.write('  </p>\n'f.write(bel for="password">Mot de passe</label><input type="password" id="password" placeholder="&#8226;&#8226;&#8226;&#8226;&#8226;&#8226;&#8226;&#8226;"></div>\n')
f.write('        <div class="form-options"><label class="checf.write('        <div class="form-options"><label class="checf.write('        <div class="form-options"><label class="checf.write('        <div class="form-options"><label class="checf.write('        <div classfof.write('        <div clp f.write('        <div  df.write('        <div class="form-options"><label class="checf.write('        <div class="form.write('    </div>\n')
f.write('  </div>\n')
f.write('</div>\n')
f.write('</body>\n</html>')
f.close()
print('OK login-v4.html genere')
